# Generated by Django 5.0.4 on 2024-05-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_categories_options_alter_products_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={
                "ordering": ("id",),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
