# Generated by Django 5.0.4 on 2024-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Количество"
            ),
        ),
    ]
